In [4]:
!pip3 install numpy

In [5]:
import numpy as np

In [2]:
np.__version__

'1.19.2'

In [6]:
a=np.array([1,2,3,4,5])

In [7]:
a

array([1, 2, 3, 4, 5])

In [8]:
b=np.array((6,7,8))

In [9]:
type(a),type(b)

(numpy.ndarray, numpy.ndarray)

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [12]:
np.arange(1.0,3.0,0.5,dtype='float64')

array([1. , 1.5, 2. , 2.5])

In [13]:
np.arange(1,20,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [14]:
np.arange(0,20,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])